### ISSUE TITLE
Agenda for Milestone 3 discussion

### ISSUE THREAD

**Issue by tdkhanhvu** [UBC-MDS/dsci532-group3-R#1]
## I) Task breakdown

|#|Task|Marks|Description|Deliverables|Assignee|
|--|--|--|--|--|--|
|1|Follow Submission Instruction (8%)|mechanics:4|<ul><li>Create a release on **GitHub.com** before the submission deadline</li><li>Submit **canvas-submission.html** once</li></ul>|canvas-submission.html|TBD|
|2|Deployment on Heroku  (16%)|accuracy:8|<ul><li>Deploy your app on Heroku</li><li>Include dashboard link clearly visible near the top of your README</li><li>Change the Procfile to **web: gunicorn src.app:server** once</li><li>Deploy early and check that things are working</li><li>After making the milestone2 release, make a final push to Heroku to redeploy the miletone2 app.</li></ul>|<ul><li>App deployed on Heroku website</li><li>New project structure</li><li>requirements.txt</li></ul>|TBD|
|3| Interactive Dash app in Python and Altair (60%)|accuracy:10</br>quality:5</br>viz:15|<ul><li>Implement the dashboard</li><li>Keep your usage scenario and target audience in mind</li><li>Implement most functionalities, not everything.</li><li>Make self-documenting interface </li><li>App on Heroku in a full-screen window</li></ul>|<ul><li>`src/download.py`</li><li>`src/app.py` (**beware of merge conflicts**)</li></ul>|TBD|
|4|Reflection (12%)|reasoning:6|<ul><li>Document implemented vs not implemented features</li><li>Relect on limitations, good future developments</li></ul>|`doc/reflection-milestone3.md`|TBD|
|5|Give feedback to another team (Optional, 4%)|reasoning:2|<ul><li>[Group 4](https://github.com/UBC-MDS/dsci_532_group_04)</li><li>Read section 1 (motivation) and 3 (usage scenario) of their proposal and maybe also skim their README</li><li>Start your feedback with 2-3 sentences describing your feedback persona and motivation/goal when using this dashboard</li></ul>|`/README.md`|TBD|

**Address on feedback from the TA** (I have fixed some)

## III) Steps for Coding

1.  Overview
- a) Display charts with all data
- b) Filter data by Region/ Country
- c) Filter data by Date / Month (Need data wrangling?)
- d) Calculate data by 1M (Need data wrangling?)
- e) Display the whole map that highlights countries / regions based on statistics
- f) Make the map clickable (optional)
5.  Comparison
- a) Display charts with all data
- b) Filter data by Region/ Country
- c) Filter data by Date / Month (Need data wrangling?)
- d) Calculate data by per capita (Need data wrangling?)
- e) Display the whole map that highlights countries / regions based on statistics
- f) Display other information (population...) on the map
- g) Make the map clickable (optional)
6. Deploy the app in Heroku (**_Do not leave until last minute_**)

## Next meeting
Wednesday 8PM?

**Comment by heidi-ye** [comment]
Progress check in Wednesday 8PM (confirm with arash on slack).
Targeted completion: Friday 8PM.

Task Breakdown:
1. Submission: Suhkdeep
2. Heroku: Vu 
3. Dashboard:
 - Vu: initial template & region/country fields
 - Heidi: radio buttons, per capita functionality (make into per million)
 - Suhkdeep: line charts & interactivity with filters
 - Aarsh: map & interactivity with filters
4. Relection: Heidi
5. Feedback: whole team to review. Arash to summarize into issue for submission.

**Comment by tdkhanhvu** [comment]
Some feedback from Chris (TA) during our lab discussion:
**Things doing well:**
- Layout in high resolution still okay
- Should not worry not too much about the speed.
- No need documentation. Very clear already. Unless we want to do clickable map -> update charts then probably

**Some suggestions already addressed:**
- Facetting -> 3 graphs (afraid of resizing the screen => smaller image)
- Quite slow for user -> Added loading screen

**Some suggestions (not that compulsory, nice to have)**
- Fancy styling -> milestone 3,4
- Click on the map -> change line charts
- Alternative option: merge all graphs in 1 place instead of 3 graphs.
- All the graphs sharing same axis.
- If dropdown list cannot expand, have a scroll bar instead of hiding inputs
He agreed that those functions may be feasible and infeasible. So I guess we can play around, and if not possible just acknowledge that we are well aware of that, have put efforts into but unable to complete due to tight deadlines.
