### ISSUE TITLE
Agenda for Milestone 4 meeting

### ISSUE THREAD

**Issue by tdkhanhvu** [UBC-MDS/dsci532-group3-R#30]
# 1. Decide on which version to be used:

|Metric|Python |R|
|--|--|--|
|Easier to write code|X||
|Response time||X|
|Features implemented||X|
|Bugs fixed||X|
|Deployment time|X||

# 2. Features to consider:
| # | Name | Description | Priority | Difficulty | Assignee |
| -- | -- | -- | -- | -- | -- |
| 1 | Layout beautification |Make the layout look fancier by adding styling / bootstrap effect | High | Easy | TBD|
| 2 | Additional line charts | 3 more: New Confirmed/ Deaths / Recovered | Medium |  Easy | TBD |
| 3 | Map metrics customization | 1 more dropdownlist to select which metrics to be displayed on the world map (Default Confirmed) | Medium | Intermediate | TBD |
| 4 | Charts beautification | Make the line charts look more attractive | Medium | Easy | TBD |
| 5 | Map selection leads to line charts changed | When clicking on a country or a bunch of countries on the map, the filtering and line charts will be updated accordingly | Low | Hard | @tdkhanhvu |

# 3. Checkpoints:
**Monday, 2PM PST:**
- **Purpose**: Initial discussion with team members and get feedback from TA
- **Deliverables**: Version chosen, features to be implemented agreed

**Wednesday, 8PM PST**:
- **Purpose**: First check point to see if everyone is on track with their tasks, and any help is required from others.
- **Deliverables**: First version of the features is finished.

**Friday, 8PM PST**:
- **Purpose**: Regroup and combine all components
- **Deliverables**: All codes and documentations to be completed. Code is deployed to Heroku.

**Comment by heidi-ye** [comment]
Decisions:
- using R for milestone 4
- Arash doing final submission
- Vu to deploy 
- app reviews (explore on Friday)

1. Layout beautification: Heidi
- nicer heading
- put plots in shaded color block
- side bar for all the selection options

2. Maps metrics (allow other metics to show up on map, currently only confirmed data shows up): Sukhdeep

3. Charts beautification & facet into one object, 3 additional Line charts: Arash 

5. Map selection: Vu 
 - single color scale instead of rainbow

6. Reflection: Heidi
 - need to include why we chose python or R

7. Updating readme for milestone 4 requirements: Arash

**Comment by tdkhanhvu** [comment]
**Feedback:**
**A) Joel**
1) Better to have same grey / white background between maps and charts (consistent)
=> Change the background of line charts to white as well

2) Color scale should be more consistent
=> Change it to red scale instead of rainbow

3) Hard to distinguish between filtering section and charts
=> Borders around filtering sections to make them stand out

**B) Chris:**
1) Adding many countries will push the whole thing down. Minor detail
=> scroll bar (possible?)
=> limit the countries to maybe 5? (It will make the graphs look busy if we add too many anyway)
=> make the dropdown list's height spans 2 lines by default instead of 1

2) Legend problem: The middle chart will shrink
=> Merge 3 charts into 1 (more feasible / easier)
=> 1 more chart without any axis, but only the legend (hack way)

3) Click on the legend on 1 chart => not updating on the other 2
Reason: They are 3 separate objects for now
=> Merging in 2) will resolve the issue
